services:
    postgres:
        image: 'docker.io/postgres:latest'
        environment:
            - POSTGRES_PASSWORD=postgres_password
            - POSTGRES_USER=postgres
            - POSTGRES_DB=simple_blog_api
        ports:
            - '5432:5432'
    api:
        build: ./
        image: docker.io/sandhyag1/simple_blog_api
        environment:
            - POSTGRES_HOST=postgres              
            - POSTGRES_PORT=5432                  
            - POSTGRES_USERNAME=postgres           
            - POSTGRES_PASSWORD=postgres_password  
            - POSTGRES_DB=simple_blog_api   
        depends_on:
            - postgres 
        ports:
            - '3000:3000'
       